name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Клонирование
      - name: Checkout code
        uses: actions/checkout@v3

      # Логин
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Запуск тестов
      - name: Run tests
        run: make test

      # Сборка
      - name: Build production image
        run: docker-compose -f docker-compose.yml build app

      # Публикация
      - name: Push image to Docker Hub
        run: docker-compose -f docker-compose.yml push app